# Generated by Django 3.2.6 on 2021-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(upload_to='banners_category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='images_products/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='banner',
            field=models.ImageField(upload_to='banners_sub_category/'),
        ),
    ]
